### ISSUE TITLE
costmap_converter/ObstacleArrayMsg.h

### ISSUE THREAD

**Issue by ponder-lxl** [janedipan/Demo-Acbf2312#1]
Hello, I have some problems when compiling. I found that the costmap_converter package does not exist in the warehouse. How can I solve it?
![image](https://github.com/janedipan/Demo-Acbf2312/assets/129484066/b1e400ae-9b9a-4fe4-aafb-94d9423178d6)

**Comment by ponder-lxl** [comment]
I have already resolved it, thank you

**Comment by pzy22** [comment]
> I have already resolved it, thank you

你好，不知道你有没有"dynamic_simulator/DynTraj.h" 文件
![image](https://github.com/janedipan/Demo-Acbf2312/assets/53420236/79f3be45-f8f1-41d3-bb93-7fc58a45c89c)
